study_center/api/urls.py
from django.urls import path, include

from .views import *

app_name = 'api'


urlpatterns = [
    path("", TeacherView.as_view()),
    path('course-register/', CoursRegisterView.as_view()),
    path('course-register/<int:pk>/', CoursRegisterView.as_view()),
    path('course/', CourseView.as_view()),
    path('course/<int:pk>/',  CourseView.as_view()),
    path('traningregister/', TrainingRegisterView.as_view()),
    path('traningregister/<int:pk>/', TrainingRegisterView.as_view()),
    path("dashboard/", include("client.urls"))
]

study_center/client/urls.py
from django.urls import path
from . import views

app_name = 'client'


urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.dashboard_login, name="login"),
    path('logout/', views.dashboard_logout, name="logout"),

    path('category_list/', views.category_list, name="category_list"),
    path('category_create/', views.category_create, name="category_create"),
    path('<int:pk>category_edit/', views.category_edit, name="category_edit"),
    path('<int:pk>/category_delete/', views.category_delete, name="category_delete"),

    path('registerr_list/', views.registerr_list, name="registerr_list"),
    path('registerr_create/', views.registerr_create, name="registerr_create"),
    path('<int:pk>registerr_edit/', views.registerr_edit, name="registerr_edit"),
    path('<int:pk>/registerr_delete/', views.registerr_delete, name="registerr_delete"),

    path('course_list/', views.course_list, name="course_list"),
    path('course_create/', views.course_create, name="course_create"),
    path('<int:pk>course_edit/', views.course_edit, name="course_edit"),
    path('<int:pk>/course_delete/', views.course_delete, name="course_delete"),

    path('training_list/', views.training_list, name="training_list"),
    path('training_create/', views.training_create, name="training_create"),
    path('<int:pk>training_edit/', views.training_edit, name="training_edit"),
    path('<int:pk>/training_delete/', views.training_delete, name="training_delete"),

    path('register_list/', views.register_list, name="register_list"),
    path('register_create/', views.register_create, name="register_create"),
    path('<int:pk>register_edit/', views.register_edit, name="register_edit"),
    path('<int:pk>/register_delete/', views.register_delete, name="register_delete"),
    
]

study_center/study_center/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path("dashboard/", include("client.urls"))

]

study_center/templates/dashboard/TrainingRegister/form.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>AboutTeacher</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">AboutTeacher</a></li>
          <li class="breadcrumb-item active">AboutTeacher</li>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
            <div class="card card-primary">

              <form method="post"  enctype="multipart/form-data">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>CourseRegister</label>
                      {{form.name}}
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>

          </div>
        </div>
    </div>
</section>
{% endblock %}

study_center/templates/dashboard/TrainingRegister/list.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Category List</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
{#                        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>#}
                        <li class="breadcrumb-item active">Category List</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Responsive Hover Table</h3>

                            <div class="card-tools">
                                <a href="{% url 'client:category_create' %}">
                                    <div class="btn btn-block btn-outline-success">Add</div>
                                </a>
                            </div>
                        </div>

                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap">
                                <thead>
                                <tr>
                                    <th>№</th>
                                    <th>Fam</th>
                                    <th>Ismi</th>
                                    <th>Category Name</th>
                                    <th>Created_at</th>


                                </tr>
                                </thead>
                                <tbody>
                                {% for i in trainingregister %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ i.first_name }}</td>
                                        <td>{{ i.last_name }}</td>
                                        <td>{{ i.middle_name }}</td>
                                        <td>{{ i.phone }}</td>
                                        <td>{{ i.email }}</td>

                                        <td><a href="{% url 'client:category_edit' pk=i.id %}">
                                            <div class="btn btn-block btn-outline-warning">Edit</div>
                                        </a></td>
                                        <td><a href="{% url 'client:category_delete' pk=i.id %}">
                                            <div class="btn btn-block btn-outline-danger ">Delete</div>
                                        </a></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>
{% endblock %}